<div></div>
<p></p>
<p><span class="dimmed"><strong><span>Implementation â†’ Error Handling â†’ Exceptions â†’
</span></strong>
  </span>
</p>
<div id="title-and-body">
  <div>
    <h4 id="how-two">How <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0032-20e3.png"></h4>
  </div>
  <div id="main">
    <div>
      <p><strong>Most languages allow a method/function to encapsulate the unusual situation in an Exception object and 'throw'/'raise' that object so that another piece of code can 'catch' it and deal with it.</strong> This is especially useful when code
        segment that encountered the unusual situation does not know how to deal with it.</p>
      <p><strong>Exception objects can propagate up the function call hierarchy until it is dealt with.</strong> Usually, an exception thrown by a function is caught by the caller function. If the called function does not know how to deal with the exception
        it caught, it can throw/raise the Exception object to its own caller. If none of the callers is prepared to deal with the exception, the exceptions can propagate through the
        <tooltip content="the hieararchy of function calls">function call stack</tooltip> until it is received by the main function and thrown to the runtime, thus halting the system.</p>
      <tip-box>
        <tabs>
        
          <tab header="Java">
            <p>ðŸ“¦ In the code given below, <code>processArray</code> can potentially throw an <code>InvalidInputException</code>. Because of that, <code>processInput</code> method invokes <code>processArray</code> method inside a <code>try{ }</code> block
              and has a <code>catch{ }</code> block to specify what to do if the exception is actually thrown.</p>
            <img src="/website-base/book/errorHandling/exceptions/how/images/processInput.png" width="400">
            <p></p>
            <p></p>
          </tab>
        
          <tab header="Python">
            <p>ðŸ“¦ In the code given below, <code>process_array</code> function can potentially raise a <code>ValueError</code> exception. Because of that, <code>process_input</code> function invokes <code>process_array</code> function inside a <code>try</code>              clause and has a <code>except</code> clause to specify what to do if the exception is actually raised.</p>
            <img src="/website-base/book/errorHandling/exceptions/how/images/example-python.png" width="400">
            <p></p>
          </tab>
        </tabs>
        <hr>
      </tip-box>
      <p>Advantages of exception handling in this way:</p>
      <ul>
        <li>The ability to propagate error information through the call stack.</li>
        <li>The separation of code that deals with 'unusual' situations from the code that does the 'usual' work.</li>
      </ul>
    </div>
    <div>
      <div>
        <panel header=":paperclip: Resources" expandable="">
          <ul>
            <li><a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/">Java Exceptions Tutorial from Oracle</a></li>
          </ul>
        </panel>
      </div>
      <div>
        <panel header=":muscle: Exercises" expandable="">
          <div>
            <panel header=":lock::key: Benefit of exceptions">
              <question>
                <p>Which are benefits of exceptions?</p>
                <ul class="task-list">
                  <li class="task-list-item"><input class="task-list-item-checkbox" type="checkbox"> a. Exceptions allow us to separate normal code from error handling code.</li>
                  <li class="task-list-item"><input class="task-list-item-checkbox" type="checkbox"> b. Exceptions can prevent problems that happen in the environment.</li>
                  <li class="task-list-item"><input class="task-list-item-checkbox" type="checkbox"> c. Exceptions allow us to handle in one location an error raised in another location.</li>
                </ul>
                <div slot="answer">
                  <p>(a) (c)</p>
                  <p>Explanation: Exceptions cannot <em>prevent</em> problems in the environment. They can only be used to handle and recover from such problems.</p>
                </div>
              </question>
            </panel>
          </div>
        </panel>
      </div>
    </div>
  </div>
</div>